# This is a basic workflow to help you get started with Actions

name: CI-CD-Pipeline
env:
  EB_PACKAGE_S3_BUCKET_NAME : "test-flask2"
  EB_APPLICATION_NAME : "test-flask2"
  EB_ENVIRONMENT_NAME : "Test-flask2-env"
  DEPLOY_PACKAGE_NAME : "flask_app${{ github.sha}}.zip
  AWS_REGION_NAME : "eu-north-1"
  

# Controls when the workflow will run
on:
  push:
    branches: 
      - master


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
 
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: git clone
      uses: actions/checkout@v1
      
    - name: create
      run: zip -r ${{ env.DEPLOY_PACKAGE_NAME }} ./ -x *.git*
