name: CI-CD-Pipeline
env:
  EB_PACKAGE_S3_BUCKET_NAME : "adv-it-flask"
  EB_APPLICATION_NAME       : "flask-app2"
  EB_ENVIRONMENT_NAME       : "Flask-app2-env"
  DEPLOY_PACKAGE_NAME       : "flask-app-${{ github.sha }}.zip"
  AWS_REGION_NAME           : "eu-central-1"

on:
  push:
    branches: 
      - test333

jobs:
  my_test:
    runs-on: ubuntu-latest

    steps:
    - name: Print hello
      run: echo "Print hello"
    - name: execure few commands
      run : |
       echo "heelo 1"
       echo "heelo 2"
       echo "${{ env.AWS_REGION_NAME }} "
      
  my_test2:
    needs: my_test
    runs-on: ubuntu-latest

    steps:
    - name: Print hello
      run: echo "Print hello"
